version: '3.8'

services: 
  main-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: zangia-test-app:latest
    container_name: test-app-src
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    entrypoint: ["sh", "-c", "php-fpm"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - main-server  

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: